version: "3.9"
services:
  php:
    build: .
    depends_on:
      - mysql
    ports:
      - "8080:80"   # Assuming your PHP app runs on port 80

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root@123
      MYSQL_DATABASE: growmore
    ports:
      - "3307:3306"   # Change host port from 3306 -> 3307
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
