services:
  php:
    build: .
    container_name: demo-php
    ports:
      - "8080:80"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root@123
      DB_NAME: growmore

  mysql:
    image: mysql:8
    container_name: demo-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root@123
      MYSQL_DATABASE: growmore
      MYSQL_USER: root
      MYSQL_PASSWORD: root@123
    ports:
      - "3307:3306"

