services:
  php:
    build: .
    container_name: demo-php
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      DB_HOST: dpg-d4176qa4d50c73dtfcq0-a.oregon-postgres.render.com
      DB_PORT: 5432
      DB_NAME: growmore_c1tn
      DB_USER: growmore_c1tn_user
      DB_PASSWORD: CjzTtIVUbsQgTVFzzlFa0vzGAOUnZggG
      DB_SSLMODE: require
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: demo-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8083:80"   # PgAdmin opens on http://localhost:8083
    restart: always
