version: '3.9'

services:
  php:
    build: .
    container_name: demo-php
    ports:
      - "8080:80"
    environment:
      DB_HOST: dpg-d4176qa4d50c73dtfcq0-a.oregon-postgres.render.com
      DB_PORT: 5432
      DB_NAME: growmore_c1tn
      DB_USER: growmore_c1tn_user
      DB_PASSWORD: CjzTtIVUbsQgTVFzzlFa0vzGAOUnZggG
      DB_SSL: require
    networks:
      - app-network
    volumes:
      - ./app:/var/www/html

  pgadmin:
    image: dpage/pgadmin4
    container_name: demo-pgadmin
    ports:
      - "8082:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@growmore.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
