version: '3.9'

services:
  php:
    build: .
    container_name: demo-php
    ports:
      - "8080:80"
    environment:
      # Optional: environment variables for local testing
      DB_HOST: localhost
      DB_PORT: 5432
      DB_NAME: growmore_c1tn
      DB_USER: growmore_c1tn_user
      DB_PASSWORD: CjzTtIVUbsQgTVFzzlFa0vzGAOUnZggG
    networks:
      - app-network
    volumes:
      - ./app:/var/www/html   # mount your PHP files

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: demo-phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_ARBITRARY: 1         # allows connecting to external DBs like Render
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
