services:
  php:
    build: .
    container_name: demo-php-1
    depends_on:
      - mysql
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html

  mysql:
    image: mysql:8
    container_name: demo-mysql-1
    environment:
      MYSQL_ROOT_PASSWORD: root@123
      MYSQL_DATABASE: growmore
    ports:
      - "3307:3306"   # Host port 3307 â†’ container port 3306
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
